# Generated by Django 3.2.3 on 2021-06-28 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_auto_20210624_1906'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['date'], 'permissions': (('can_mark_returned', 'Set order as returned'),)},
        ),
        migrations.AlterField(
            model_name='booking',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
