# Generated by Django 3.2.3 on 2021-06-28 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_auto_20210624_1906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoriteproduct',
            name='is_favorited',
        ),
        migrations.AlterField(
            model_name='booking',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
